[project]
name = "gather-codes"
version = "0.1.0"
description = "Access muni code publisher web sites more efficiently"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playwright>=1.55.0",
    "requests>=2.32.5",
]
